apiVersion: v2
appVersion: v3.13.0
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.27.0
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.6.7
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.12.2
description: "Open-source customer engagement suite, an alternative to Intercom, Zendesk, Salesforce Service Cloud etc. 🔥💬"
home: https://github.com/chatwoot/charts
icon: https://chatwoot-public-assets.s3.amazonaws.com/logo/square.png
keywords:
  - chatwoot
  - open source
  - customer support
  - chat
  - ruby
  - rails
  - crm
maintainers:
  - email: vishnu@chatwoot.com
    name: vishnu-narayanan
  - email: sojan@chatwoot.com
    name: sojan-official
name: chatwoot
sources:
  - https://github.com/chatwoot/chatwoot
  - http://www.chatwoot.com
type: application
version: 1.1.15
